GET http://localhost:3000/api/hello HTTP/1.1

###

POST http://localhost:3000/api/chats HTTP/1.1
Content-Type: application/json

{
    "message": "hello, world"
}

###

GET http://localhost:3000/api/chats HTTP/1.1
Content-Type: application/json

###
@chatId = b16c3ab6-6103-459f-b6b8-06b0c97708f7

GET http://localhost:3000/api/chats/{{chatId}}/messages

###

POST http://localhost:3000/api/chats/{{chatId}}/messages
Content-Type: application/json

{
    "message": "Estou testando a API"
}

###
@messageId = 650edfb8-e63a-468f-b70b-32f036c75178
GET http://localhost:3000/api/messages/{{messageId}}/events